/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 smile.glb
Author: Yan (https://sketchfab.com/yanbatsman)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/old-shabby-smile-c346c0c8635f48f381adcae5172348ea
Title: Old shabby smile
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/smile.glb');
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0, 98.28, 0]}>
          <mesh
            geometry={nodes['����������_2_2_����������������1_0'].geometry}
            material={materials.material_2}
          />
          <mesh
            geometry={nodes['����������_2_2_����������������1_0_1'].geometry}
            material={materials.material_2}
          />
          <mesh
            geometry={nodes['����������_2_2_����������������1_0_2'].geometry}
            material={materials.material_2}
          />
        </group>
        <mesh
          geometry={nodes['����������_2_����������������_0'].geometry}
          material={materials.material}
          position={[64.52, 125.33, 25.69]}
        />
        <mesh
          geometry={nodes['����������_1_����������������_0'].geometry}
          material={materials.material}
          position={[64.52, 125.33, -27.39]}
        />
        <mesh
          geometry={nodes['����������_����������������2_0'].geometry}
          material={materials.material_1}
          position={[84.1, 54.85, -39.2]}
        />
        <mesh
          geometry={nodes['hjn_����������������2_0'].geometry}
          material={materials.material_1}
          position={[121.21, 72.88, 6.84]}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/smile.glb');
