/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Smiley.glb
*/

// import React, { useRef } from "react";
// import { useGLTF } from "@react-three/drei";

// export default function Model(props) {
// 	const { scene } = useGLTF("/smileyTwo.glb");

// 	return <primitive object={scene} {...props} />;
// }

// useGLTF.preload("/smileyTwo.glb");
