/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Smiley.glb
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Smiley.glb');
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0, 98.28, 0]}>
          <mesh
            geometry={nodes['����������_2_2_��������'].geometry}
            material={materials.material_2}
          />
          <mesh
            geometry={nodes['����������_2_2_��������001'].geometry}
            material={materials.material_2}
          />
          <mesh
            geometry={nodes['����������_2_2_���������'].geometry}
            material={materials.material_2}
          />
        </group>
        <mesh
          geometry={nodes['hjn_����������������2_0'].geometry}
          material={materials.material_1}
          position={[121.21, 72.88, 6.84]}
        />
        <mesh
          geometry={nodes['����������_����������'].geometry}
          material={materials.material_1}
          position={[84.1, 54.85, -39.2]}
        />
        <mesh
          geometry={nodes['����������_1_����������'].geometry}
          material={materials.material}
          position={[64.52, 125.33, -27.39]}
        />
        <mesh
          geometry={nodes['����������_2_����������'].geometry}
          material={materials.material}
          position={[64.52, 125.33, 25.69]}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/Smiley.glb');
